version: "3"
services:
  mysql:
    image: mysql:8
    env_file:
      - .env
    ports:
      - '8888:3306'
    environment:
      MYSQL_DATABASE: bikes
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 20s
      retries: 3

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      sh -c "./create_superuser.sh && python manage.py runserver 0.0.0.0:8000"
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
